import useProducts from '@/hooks/use-product'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { ReactElement, JSXElementConstructor, ReactFragment, ReactPortal, Key } from 'react'
import Header from '../components/Header'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const { data: products, error, create, remove} = useProducts()
  if (!products) return <div>loading...</div>;
   if (error) return <div>error</div>;
  return (
    <div className={styles.container}>
      {/* <Head>
        <title>Hi Linhlt02 </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      {/* <Header></Header> */}

      {products.map((product: { name: string | number | boolean | ReactElement<any, string | JSXElementConstructor<any>> | ReactFragment | ReactPortal | null | undefined; id: any }, index: Key | null | undefined) => (
        <div key={index}>{product.name} <button onClick={() => remove(product.id)}>Delete</button></div>
      ))}
      <button onClick={() => create({id: 12, name: "product 12"})}>Create</button>
    <div>Main</div>
    </div>
  )
}

export default Home
